version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: flix-backend
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/flixdb?authSource=admin
      - PORT=4000
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    container_name: flix-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app

volumes:
  mongo-data:

